### ISSUE TITLE
Bug: property console is not registered, declare it as `inject` to suppress this warning

### ISSUE THREAD

**Issue by idranme** [koishijs/koishi-plugin-downloads#2]
```
[W] app Error: property console is not registered, declare it as `inject` to suppress this warning
                            at checkInject (D:\develop\koishi-dev\node_modules\cordis\src\context.ts:108:38)
                            at Object.get (D:\develop\koishi-dev\node_modules\cordis\src\context.ts:124:32)
                            at Proxy.refresh (D:\develop\koishi-dev\node_modules\koishi-plugin-downloads\lib\service.js:16:22)
                            at D:\develop\koishi-dev\node_modules\koishi-plugin-downloads\lib\tasks.js:112:28
                            at EventEmitter.emit (D:\develop\koishi-dev\node_modules\nereid\lib\events.js:27:22)
                            at startSync (D:\develop\koishi-dev\node_modules\nereid\lib\resolve\index.js:128:15)
```

**Comment by xmbhjQAQ** [comment]
同样的问题.png
